### ISSUE TITLE
upgraded sinatra doens't default with server

### ISSUE THREAD

**Issue by eengstrom** [Scronkfinkle/quick-secrets#22]
As configured currently, will fail with:
```
detect_rack_handler: Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)
```

Installing `thin` works, but should probably pick one.

**Comment by Scronkfinkle** [comment]
Sinatra used to ship by default with WEBrick. So for consistency, I'll make that the default this gem uses
