### ISSUE TITLE
Double-click on unlock results in lost secret

### ISSUE THREAD

**Issue by eengstrom** [Scronkfinkle/quick-secrets#23]
In addition to #19, if someone clicks twice on the "unlock" button, the secret will be first decrypted, and deleted, and then the second time, since it no longer exists, the response is "Invalid Password".

Suggestions:
  - replace the entire "passphrase" field and "unlock/burn" buttons with the decyrpted secret
  - the phrase "invalid password" implies that there was a secret. why not just say "no such secret"?

**Comment by Scronkfinkle** [comment]
> replace the entire "passphrase" field and "unlock/burn" buttons with the decyrpted secret  

Good suggestion, will implement

> the phrase "invalid password" implies that there was a secret. why not just say "no such secret"?  

Lazy implementation. This check happens when the page is rendered. The workflow breaks when you try re-submit though since the page doesn't refresh. Implementing the first suggestion will resolve this
