### ISSUE TITLE
fix token-based API access

### ISSUE THREAD

**Issue by eengstrom** [Scronkfinkle/quick-secrets#7]
Token-based access is busted.  Busted, because sessions expiration is checked, but no session will ever exist for token-based sessions (yet).

See, esp., line 179 of auth.rb

**Comment by Scronkfinkle** [comment]
I'm curious on how one should go about fixing this. The first option I can think of is simply to add a conditional check for the session token and if present ignore expiration dates. That seems a bit flimsy at surface value, but I don't think we'll be adding too many forms of authentication so it may not be too bad to implement that way.

Another solution would be to add in expiration times on token auth, but that seems like a much more finicky solution

**Comment by eengstrom** [comment]
I was going to go with the first option - if a token is provided, the session is only as long as the current request. Every token-based session needs a token - no cookies.

The alternative is a login approach and requires that cookies be stored on the client - more work.

**Comment by Scronkfinkle** [comment]
To solve this, I simply switched the order to check for token auth first, then treat expiration as part of the session-only validation; probably should have done that in the first place...
