### ISSUE TITLE
Request : Shortened URL

### ISSUE THREAD

**Issue by jhamell** [Scronkfinkle/quick-secrets#8]
The current URL generation produces a unique 64 character path suffix.

Would it be possible to shorten this value without compromising security?  I'm looking at the trivial but non-uncommon use case of cut-and-paste errors.

**Comment by Scronkfinkle** [comment]
The current URL generation is just a SHA256 hash of the encrypted password.  

I can think of two ways to solve this. The first is to just use a shortened SHA, which are p reliable when it comes to avoiding collisions. Alternatively, it probably wouldn't be too hard, and more secure to just have it randomly generate a smaller string for each link creation.

**Comment by jhamell** [comment]
Thank you!
