### ISSUE TITLE
Adjust or adjustable session timeout

### ISSUE THREAD

**Issue by eengstrom** [Scronkfinkle/quick-secrets#9]
The current timeout seems really short (like < 1 min???) - can we make it longer?  Make it adjustable by config?

**Comment by Scronkfinkle** [comment]
it is adjustable by configuration. Refer to the [Configuration section of the README](https://github.com/Scronkfinkle/quick-secrets#configurationl)  

You can set the field `session_expiration` in your `config.yml` or set the environment variable `QUICK_SECRETS_SESSION_EXPIRATION`
